<template>
  <div class="exam-paper-management">
    <el-card class="mb-4">
      <template #header>
        <div class="card-header">
          <span>试卷列表</span>
          <div class="header-actions">
            <el-button
              type="danger"
              @click="handleBatchDelete"
              :disabled="selectedPaperIds.length === 0"
            >
              <el-icon><Delete /></el-icon>
              批量删除
            </el-button>
            <el-button type="primary" @click="handleAddPaper">
              <el-icon><Plus /></el-icon>
              添加试卷
            </el-button>
            <el-button type="success" @click="handleAutoGeneratePaper">
              <el-icon><MagicStick /></el-icon>
              自动组卷
            </el-button>
          </div>
        </div>
      </template>

      <el-table
        :data="papers"
        border
        stripe
        @selection-change="handleSelectionChange"
      >
        <el-table-column type="selection" width="55" />
        <el-table-column prop="paperId" label="试卷ID" width="80" />
        <el-table-column prop="paperName" label="试卷名称" width="200" />
        <el-table-column prop="courseId" label="课程ID" width="80" />
        <el-table-column prop="totalScore" label="总分" width="80" />
        <el-table-column prop="createTime" label="创建时间" width="180" />
        <el-table-column label="操作" width="250" fixed="right">
          <template #default="scope">
            <el-button
              type="primary"
              size="small"
              @click="handleEditPaper(scope.row)"
            >
              <el-icon><Edit /></el-icon>
              编辑
            </el-button>
            <el-button
              type="danger"
              size="small"
              @click="handleDeletePaper(scope.row.paperId)"
            >
              <el-icon><Delete /></el-icon>
              删除
            </el-button>
            <el-button
              type="success"
              size="small"
              @click="handleViewPaper(scope.row.paperId)"
            >
              <el-icon><View /></el-icon>
              查看
            </el-button>
            <el-button
              type="warning"
              size="small"
              @click="handleManageQuestions(scope.row.paperId)"
            >
              <el-icon><List /></el-icon>
              题目管理
            </el-button>
          </template>
        </el-table-column>
      </el-table>

      <div class="pagination mt-4">
        <el-pagination
          v-model:current-page="currentPage"
          v-model:page-size="pageSize"
          :page-sizes="[10, 20, 50, 100]"
          layout="total, sizes, prev, pager, next, jumper"
          :total="total"
          @size-change="handleSizeChange"
          @current-change="handleCurrentChange"
        />
      </div>
    </el-card>

    <!-- 试卷表单对话框 -->
    <el-dialog v-model="dialogVisible" :title="dialogTitle" width="600px">
      <el-form :model="paperForm" label-width="120px">
        <el-form-item label="试卷名称" required>
          <el-input
            v-model="paperForm.paperName"
            placeholder="请输入试卷名称"
          />
        </el-form-item>
        <el-form-item label="所属课程" required>
          <el-select v-model="paperForm.courseId" placeholder="请选择课程">
            <el-option
              v-for="course in courses"
              :key="course.courseId"
              :label="course.courseName"
              :value="course.courseId"
            />
          </el-select>
        </el-form-item>
        <el-form-item label="总分" required>
          <el-input
            v-model.number="paperForm.totalScore"
            placeholder="请输入试卷总分"
            type="number"
            min="0"
            step="0.5"
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <span class="dialog-footer">
          <el-button @click="dialogVisible = false">取消</el-button>
          <el-button type="primary" @click="handleSavePaper">确定</el-button>
        </span>
      </template>
    </el-dialog>

    <!-- 自动组卷对话框 -->
    <el-dialog
      v-model="autoGenerateDialogVisible"
      title="自动组卷"
      width="800px"
    >
      <el-form :model="autoGenerateForm" label-width="120px">
        <el-form-item label="试卷名称" required>
          <el-input
            v-model="autoGenerateForm.paperName"
            placeholder="请输入试卷名称"
          />
        </el-form-item>
        <el-form-item label="所属课程" required>
          <el-select
            v-model="autoGenerateForm.courseId"
            placeholder="请选择课程"
            @change="handleCourseChange"
          >
            <el-option
              v-for="course in courses"
              :key="course.courseId"
              :label="course.courseName"
              :value="course.courseId"
            />
          </el-select>
        </el-form-item>
        <el-form-item label="总分" required>
          <el-input
            v-model.number="autoGenerateForm.totalScore"
            placeholder="请输入试卷总分"
            type="number"
            min="0"
            step="0.5"
          />
        </el-form-item>
        <el-form-item label="难度分布" required>
          <div class="difficulty-distribution">
            <el-form-item label="简单" required>
              <el-slider
                v-model="autoGenerateForm.difficultyDistribution['简单']"
                :min="0"
                :max="1"
                :step="0.1"
                show-input
                :input-format="(value) => value * 100 + '%'"
              />
            </el-form-item>
            <el-form-item label="中等" required>
              <el-slider
                v-model="autoGenerateForm.difficultyDistribution['中等']"
                :min="0"
                :max="1"
                :step="0.1"
                show-input
                :input-format="(value) => value * 100 + '%'"
              />
            </el-form-item>
            <el-form-item label="困难" required>
              <el-slider
                v-model="autoGenerateForm.difficultyDistribution['困难']"
                :min="0"
                :max="1"
                :step="0.1"
                show-input
                :input-format="(value) => value * 100 + '%'"
              />
            </el-form-item>
          </div>
        </el-form-item>
        <el-form-item label="知识点权重" required>
          <el-table :data="autoGenerateForm.knowledgePointWeights" border>
            <el-table-column prop="pointId" label="知识点ID" width="100" />
            <el-table-column prop="pointName" label="知识点名称" width="200" />
            <el-table-column label="权重" width="200">
              <template #default="scope">
                <el-slider
                  v-model="scope.row.weight"
                  :min="0"
                  :max="1"
                  :step="0.01"
                  show-input
                  :input-format="(value) => value * 100 + '%'"
                />
              </template>
            </el-table-column>
          </el-table>
        </el-form-item>
      </el-form>
      <template #footer>
        <span class="dialog-footer">
          <el-button @click="autoGenerateDialogVisible = false">取消</el-button>
          <el-button type="primary" @click="handleGeneratePaper"
            >生成试卷</el-button
          >
        </span>
      </template>
    </el-dialog>

    <!-- 题目管理对话框 -->
    <el-dialog
      v-model="questionManageDialogVisible"
      :title="`试卷题目管理 - ${currentPaperId}`"
      width="1000px"
    >
      <div class="question-manage-header">
        <el-button type="primary" @click="handleAddQuestion"
          >添加题目</el-button
        >
        <el-button
          type="danger"
          @click="handleClearQuestions"
          :disabled="paperQuestions.length === 0"
          >清空题目</el-button
        >
      </div>

      <el-table :data="paperQuestions" border stripe style="margin-top: 20px">
        <el-table-column prop="questionOrder" label="题目顺序" width="100" />
        <el-table-column
          prop="question.questionType"
          label="题目类型"
          width="100"
        >
          <template #default="scope">
            {{
              scope.row.question?.questionType === 1
                ? "单选题"
                : scope.row.question?.questionType === 2
                ? "多选题"
                : scope.row.question?.questionType === 3
                ? "判断题"
                : scope.row.question?.questionType === 4
                ? "填空题"
                : scope.row.question?.questionType === 5
                ? "简答题"
                : "未知"
            }}
          </template>
        </el-table-column>
        <el-table-column
          prop="question.questionContent"
          label="题目内容"
          min-width="300"
        >
          <template #default="scope">
            <div
              v-if="scope.row.question"
              v-html="scope.row.question.questionContent"
            ></div>
          </template>
        </el-table-column>
        <el-table-column prop="question.difficulty" label="难度" width="100" />
        <el-table-column prop="questionScore" label="分数" width="100">
          <template #default="scope">
            <el-input-number
              v-model="scope.row.questionScore"
              :min="0"
              :step="0.5"
              style="width: 100%"
            />
          </template>
        </el-table-column>
        <el-table-column label="操作" width="150" fixed="right">
          <template #default="scope">
            <el-button
              type="danger"
              size="small"
              @click="handleRemoveQuestion(scope.row.detailId)"
            >
              <el-icon><Delete /></el-icon>
              删除
            </el-button>
          </template>
        </el-table-column>
      </el-table>

      <template #footer>
        <span class="dialog-footer">
          <el-button @click="questionManageDialogVisible = false"
            >关闭</el-button
          >
        </span>
      </template>
    </el-dialog>

    <!-- 添加题目对话框 -->
    <el-dialog
      v-model="addQuestionDialogVisible"
      title="添加题目到试卷"
      width="800px"
    >
      <el-table
        :data="availableQuestions"
        border
        stripe
        @selection-change="handleQuestionSelectionChange"
        style="margin-bottom: 20px"
      >
        <el-table-column type="selection" width="55" />
        <el-table-column prop="questionId" label="题目ID" width="100" />
        <el-table-column prop="questionContent" label="题目内容" width="400" />
        <el-table-column prop="difficulty" label="难度" width="100" />
        <el-table-column prop="score" label="建议分数" width="100" />
      </el-table>

      <template #footer>
        <span class="dialog-footer">
          <el-button @click="addQuestionDialogVisible = false">取消</el-button>
          <el-button type="primary" @click="handleConfirmAddQuestion"
            >确定添加</el-button
          >
          >
        </span>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, onMounted, reactive, watch } from "vue";
import {
  Plus,
  Edit,
  Delete,
  View,
  List,
  MagicStick,
} from "@element-plus/icons-vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { getAllCourses } from "../api/course";
import {
  getAllKnowledgePoints,
  getKnowledgePointsByCourseId,
} from "../api/knowledgePoint";
import { getQuestionsByCourseId } from "../api/question";
import {
  getExamPapers,
  addExamPaper,
  updateExamPaper,
  deleteExamPaper,
  deleteExamPaperBatch,
  autoGeneratePaper,
  getPaperQuestions,
  addQuestionToPaper,
  removeQuestionFromPaper,
  clearPaperQuestions,
} from "../api/examPaper";

// 表格数据
const papers = ref([]);
const total = ref(0);
const currentPage = ref(1);
const pageSize = ref(10);
const selectedPaperIds = ref([]);

// 对话框
const dialogVisible = ref(false);
const dialogTitle = ref("添加试卷");
const paperForm = reactive({
  paperId: null,
  paperName: "",
  courseId: null,
  totalScore: 100,
  paperType: "手动组卷",
  createTeacher: "1", // 示例教师ID
});

// 自动组卷对话框
const autoGenerateDialogVisible = ref(false);
const autoGenerateForm = reactive({
  paperName: "",
  courseId: null,
  totalScore: 100,
  difficultyDistribution: {
    简单: 0.3,
    中等: 0.5,
    困难: 0.2,
  },
  knowledgePointWeights: [],
});

// 课程和知识点数据
const courses = ref([]);
const allKnowledgePoints = ref([]);

// 获取课程列表
const fetchCourses = async () => {
  try {
    const response = await getAllCourses();
    console.log("获取到的课程列表:", response);
    courses.value = response;
  } catch (error) {
    console.error("获取课程列表失败:", error);
    ElMessage.error("获取课程列表失败");
  }
};

// 获取知识点列表
const fetchKnowledgePoints = async () => {
  try {
    const response = await getAllKnowledgePoints();
    console.log("原始知识点数据:", response);
    // 将后端的kpId和kpName转换为前端需要的pointId和pointName
    allKnowledgePoints.value = response.map((point) => ({
      pointId: point.kpId,
      pointName: point.kpName,
      courseId: point.courseId,
      parentId: point.parentId,
      description: point.description,
      difficulty: point.difficulty,
      createTime: point.createTime,
      updateTime: point.updateTime,
    }));
    console.log("转换后的知识点数据:", allKnowledgePoints.value);
  } catch (error) {
    console.error("获取知识点列表失败:", error);
    ElMessage.error("获取知识点列表失败");
  }
};

// 获取试卷列表
const fetchPapers = async () => {
  try {
    const response = await getExamPapers(currentPage.value, pageSize.value);
    papers.value = response.records;
    total.value = response.total;
  } catch (error) {
    ElMessage.error("获取试卷列表失败");
    console.error("获取试卷列表失败:", error);
  }
};

// 分页处理
const handleSizeChange = (size) => {
  pageSize.value = size;
  fetchPapers();
};

const handleCurrentChange = (page) => {
  currentPage.value = page;
  fetchPapers();
};

// 选择处理
const handleSelectionChange = (selection) => {
  selectedPaperIds.value = selection.map((item) => item.paperId);
};

// 课程变化时更新知识点列表
const handleCourseChange = async (courseId) => {
  console.log("选择的课程ID:", courseId, "类型:", typeof courseId);

  if (!courseId) {
    autoGenerateForm.knowledgePointWeights = [];
    return;
  }

  try {
    // 直接调用API获取该课程的知识点，而不是从所有知识点中过滤
    const response = await getKnowledgePointsByCourseId(courseId);
    console.log("直接获取的课程知识点:", response);

    // 检查response是否为数组
    if (!Array.isArray(response)) {
      console.error("API返回的不是数组:", response);
      autoGenerateForm.knowledgePointWeights = [];
      ElMessage.warning("获取知识点数据格式错误");
      return;
    }

    // 将后端的kpId和kpName转换为前端需要的pointId和pointName
    const courseKnowledgePoints = response
      .filter((point) => point && point.kpId && point.kpName) // 过滤掉无效数据
      .map((point) => ({
        pointId: point.kpId,
        pointName: point.kpName,
        courseId: point.courseId,
        parentId: point.parentId,
        description: point.description,
        difficulty: point.difficulty,
        createTime: point.createTime,
        updateTime: point.updateTime,
      }));

    console.log("转换后的课程知识点:", courseKnowledgePoints);

    // 初始化知识点权重
    if (courseKnowledgePoints.length > 0) {
      // 根据知识点数量和难度分布随机生成权重，确保总和为1.0
      const weights = [];
      const totalPoints = courseKnowledgePoints.length;
      let remainingWeight = 1.0;

      // 为前n-1个知识点随机生成权重
      for (let i = 0; i < totalPoints - 1; i++) {
        // 每个知识点的权重范围在0.01到remainingWeight之间，确保至少有0.01的权重
        const maxWeight = remainingWeight - (totalPoints - 1 - i) * 0.01;
        const weight = parseFloat((Math.random() * maxWeight).toFixed(2));
        weights.push(weight);
        remainingWeight -= weight;
      }

      // 最后一个知识点的权重为剩余权重
      weights.push(parseFloat(remainingWeight.toFixed(2)));

      // 打乱权重顺序
      for (let i = weights.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [weights[i], weights[j]] = [weights[j], weights[i]];
      }

      // 分配权重给知识点
      autoGenerateForm.knowledgePointWeights = courseKnowledgePoints.map(
        (point, index) => ({
          pointId: point.pointId,
          pointName: point.pointName,
          weight: weights[index],
        })
      );

      console.log(
        "初始化的知识点权重:",
        autoGenerateForm.knowledgePointWeights
      );

      // 验证权重总和
      const weightSum = autoGenerateForm.knowledgePointWeights.reduce(
        (sum, item) => sum + item.weight,
        0
      );
      console.log("权重总和:", weightSum);
    } else {
      autoGenerateForm.knowledgePointWeights = [];
      ElMessage.warning("该课程下暂无知识点数据");
    }
  } catch (error) {
    console.error("获取课程知识点失败:", error);
    ElMessage.error("获取课程知识点失败");
    autoGenerateForm.knowledgePointWeights = [];
  }
};

// 批量删除
const handleBatchDelete = async () => {
  try {
    await ElMessageBox.confirm(
      `确定要删除选中的 ${selectedPaperIds.value.length} 份试卷吗？`,
      "删除确认",
      {
        confirmButtonText: "确定",
        cancelButtonText: "取消",
        type: "warning",
      }
    );

    await deleteExamPaperBatch(selectedPaperIds.value);
    ElMessage.success("批量删除成功");
    selectedPaperIds.value = [];
    fetchPapers();
  } catch (error) {
    if (error !== "cancel") {
      ElMessage.error("批量删除失败");
      console.error("批量删除失败:", error);
    }
  }
};

// 添加试卷
const handleAddPaper = () => {
  dialogTitle.value = "添加试卷";
  resetPaperForm();
  dialogVisible.value = true;
};

// 编辑试卷
const handleEditPaper = (row) => {
  dialogTitle.value = "编辑试卷";
  Object.assign(paperForm, row);
  dialogVisible.value = true;
};

// 保存试卷
const handleSavePaper = async () => {
  try {
    if (paperForm.paperId) {
      // 更新试卷
      await updateExamPaper(paperForm.paperId, paperForm);
      ElMessage.success("试卷更新成功");
    } else {
      // 添加试卷
      await addExamPaper(paperForm);
      ElMessage.success("试卷添加成功");
    }
    dialogVisible.value = false;
    fetchPapers();
  } catch (error) {
    ElMessage.error(paperForm.paperId ? "试卷更新失败" : "试卷添加失败");
    console.error("保存试卷失败:", error);
  }
};

// 删除试卷
const handleDeletePaper = async (paperId) => {
  try {
    await ElMessageBox.confirm("确定要删除该试卷吗？", "删除确认", {
      confirmButtonText: "确定",
      cancelButtonText: "取消",
      type: "warning",
    });

    await deleteExamPaper(paperId);
    ElMessage.success("试卷删除成功");
    fetchPapers();
  } catch (error) {
    if (error !== "cancel") {
      ElMessage.error("试卷删除失败");
      console.error("删除试卷失败:", error);
    }
  }
};

// 查看试卷
const handleViewPaper = (paperId) => {
  ElMessage.info(`查看试卷功能开发中，试卷ID: ${paperId}`);
};

// 题目管理相关数据
const questionManageDialogVisible = ref(false);
const addQuestionDialogVisible = ref(false);
const currentPaperId = ref(null);
const paperQuestions = ref([]);
const availableQuestions = ref([]);
const selectedQuestions = ref([]);

// 获取试卷题目列表
const fetchPaperQuestions = async (paperId) => {
  try {
    const response = await getPaperQuestions(paperId);
    paperQuestions.value = response;
  } catch (error) {
    ElMessage.error("获取试卷题目列表失败");
    console.error("获取试卷题目列表失败:", error);
  }
};

// 题目管理
const handleManageQuestions = (paperId) => {
  currentPaperId.value = paperId;
  fetchPaperQuestions(paperId);
  questionManageDialogVisible.value = true;
};

// 添加题目
const handleAddQuestion = async () => {
  try {
    // 获取当前试卷信息
    const currentPaper = papers.value.find(
      (paper) => paper.paperId === currentPaperId.value
    );
    if (currentPaper) {
      // 根据课程ID获取可用题目
      const questions = await getQuestionsByCourseId(currentPaper.courseId);
      // 过滤掉已添加到试卷的题目
      const existingQuestionIds = paperQuestions.value.map(
        (item) => item.questionId
      );
      availableQuestions.value = questions.filter(
        (question) => !existingQuestionIds.includes(question.questionId)
      );
    }
    addQuestionDialogVisible.value = true;
  } catch (error) {
    ElMessage.error("获取可用题目失败");
    console.error("获取可用题目失败:", error);
  }
};

// 处理题目选择
const handleQuestionSelectionChange = (selection) => {
  selectedQuestions.value = selection;
};

// 确认添加题目
const handleConfirmAddQuestion = async () => {
  try {
    if (selectedQuestions.value.length === 0) {
      ElMessage.warning("请至少选择一道题目");
      return;
    }

    // 批量添加题目到试卷
    const promises = selectedQuestions.value.map((question) => {
      return addQuestionToPaper({
        paperId: currentPaperId.value,
        questionId: question.questionId,
        questionOrder:
          paperQuestions.value.length +
          1 +
          selectedQuestions.value.indexOf(question),
        questionScore: question.score || 10, // 默认分数
      });
    });

    await Promise.all(promises);
    ElMessage.success("题目添加成功");
    addQuestionDialogVisible.value = false;
    // 刷新试卷题目列表
    fetchPaperQuestions(currentPaperId.value);
  } catch (error) {
    ElMessage.error("题目添加失败");
    console.error("添加题目失败:", error);
  }
};

// 移除题目
const handleRemoveQuestion = async (id) => {
  try {
    await removeQuestionFromPaper(id);
    ElMessage.success("题目删除成功");
    fetchPaperQuestions(currentPaperId.value);
  } catch (error) {
    ElMessage.error("题目删除失败");
    console.error("删除题目失败:", error);
  }
};

// 清空题目
const handleClearQuestions = async () => {
  try {
    await ElMessageBox.confirm("确定要清空该试卷的所有题目吗？", "清空确认", {
      confirmButtonText: "确定",
      cancelButtonText: "取消",
      type: "warning",
    });

    await clearPaperQuestions(currentPaperId.value);
    ElMessage.success("题目清空成功");
    fetchPaperQuestions(currentPaperId.value);
  } catch (error) {
    if (error !== "cancel") {
      ElMessage.error("题目清空失败");
      console.error("清空题目失败:", error);
    }
  }
};

// 自动组卷
const handleAutoGeneratePaper = async () => {
  resetAutoGenerateForm();
  autoGenerateDialogVisible.value = true;

  // 如果courseId已设置，确保知识点权重被正确初始化
  if (autoGenerateForm.courseId) {
    await handleCourseChange(autoGenerateForm.courseId);
  }
};

// 生成试卷
const handleGeneratePaper = async () => {
  try {
    // 转换知识点权重格式
    const knowledgePointWeights = autoGenerateForm.knowledgePointWeights.reduce(
      (map, item) => {
        map[item.pointId] = item.weight;
        return map;
      },
      {}
    );

    // 调用自动组卷API
    const params = {
      paperName: autoGenerateForm.paperName,
      courseId: autoGenerateForm.courseId,
      totalScore: autoGenerateForm.totalScore,
      knowledgePointWeights: knowledgePointWeights,
      difficultyDistribution: autoGenerateForm.difficultyDistribution,
    };

    const response = await autoGeneratePaper(params);
    if (response.success) {
      ElMessage.success(`试卷生成成功，ID: ${response.paperId}`);
      autoGenerateDialogVisible.value = false;
      fetchPapers();
    } else {
      ElMessage.error("试卷生成失败: " + (response.error || "未知错误"));
    }
  } catch (error) {
    ElMessage.error("试卷生成失败");
    console.error("生成试卷失败:", error);
  }
};

// 重置试卷表单
const resetPaperForm = () => {
  Object.assign(paperForm, {
    paperId: null,
    paperName: "",
    courseId: courses.value.length > 0 ? courses.value[0].courseId : null,
    totalScore: 100,
    paperType: "手动组卷",
    createTeacher: "1",
  });
};

// 重置自动组卷表单
const resetAutoGenerateForm = () => {
  Object.assign(autoGenerateForm, {
    paperName: "",
    courseId: courses.value.length > 0 ? courses.value[0].courseId : null,
    totalScore: 100,
    difficultyDistribution: {
      简单: 0.3,
      中等: 0.5,
      困难: 0.2,
    },
    knowledgePointWeights: [],
  });
};

// 页面挂载时获取数据
onMounted(async () => {
  // 确保fetchPapers函数能被调用，即使其他函数调用失败
  await Promise.allSettled([
    fetchCourses(),
    fetchKnowledgePoints(),
    fetchPapers(),
  ]);
});
</script>

<style scoped>
.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.header-actions {
  display: flex;
  align-items: center;
}

.mb-4 {
  margin-bottom: 16px;
}

.mt-4 {
  margin-top: 16px;
  display: flex;
  justify-content: center;
}

.difficulty-distribution {
  display: flex;
  flex-direction: column;
  gap: 20px;
}
</style>
